name: Build and Test

on:
  push:
    branches: [ "master", "*/**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # RELEASE - Linux
          - os: ubuntu-latest
            build_type: Release
            compiler: g++
          - os: ubuntu-latest
            build_type: Release
            compiler: clang++
          # RELEASE - Windows
          - os: windows-latest
            build_type: Release
            compiler: cl
          - os: windows-2025
            build_type: Release
            compiler: g++
          # DEBUG
          - os: ubuntu-latest
            build_type: Debug
            compiler: g++
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup dependencies (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        g++ --version
        cmake --version

    - name: Configure with CMake
      run: >
        cmake -B build
        -S ${{ github.workspace }}
        ${{ runner.os == 'Windows' && matrix.compiler == 'g++' && '-G Ninja' || '' }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        -DENABLE_STATIC=ON
        -DBUILD_TESTS=ON
        -DBUILD_TESTS_EXTRA=ON
        -DBUILD_EXECUTABLES_EXTRA=ON
        
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.compiler }}-artifacts
        path: build/
        retention-days: 1

  test:
    runs-on: ${{ matrix.os }}
    needs: build
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          # RELEASE - Linux
          - os: ubuntu-latest
            build_type: Release
            compiler: g++
          - os: ubuntu-latest
            build_type: Release
            compiler: clang++
          # RELEASE - Windows
          - os: windows-latest
            build_type: Release
            compiler: cl
          - os: windows-2025
            build_type: Release
            compiler: g++
          # DEBUG
          - os: ubuntu-latest
            build_type: Debug
            compiler: g++
          
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.compiler }}-artifacts
        path: build/
        
    - name: Fix permissions (Linux)
      if: ${{ runner.os == 'Linux' }}
      working-directory: ./build
      run: chmod +x casanchess tests perft

    - name: Tests - Unit and Perft
      working-directory: ./build
      run: |
        EXTENSION_SUFFIX=${{ runner.os == 'Windows' && '.exe' || '' }}
        BASE_PATH=${{ runner.os == 'Windows' && matrix.compiler == 'cl' && format('{0}/', matrix.build_type) || '' }}

        for exe_name in tests perft; do
          ./${BASE_PATH}${exe_name}${EXTENSION_SUFFIX}
        done

    - name: Bench
      working-directory: ./build
      run: |
        EXTENSION_SUFFIX=${{ runner.os == 'Windows' && '.exe' || '' }}
        BASE_PATH=${{ runner.os == 'Windows' && matrix.compiler == 'cl' && format('{0}/', matrix.build_type) || '' }}

        echo bench | ./${BASE_PATH}casanchess${EXTENSION_SUFFIX}
